### ISSUE TITLE
Custom Server

### ISSUE THREAD

**Issue by fnandomaia** [Barbayar/EasyBlynk8266#2]
Hi!
Nice job!

How to set a custom Blynk server/port ?

Thanks!

**Comment by dashbar** [comment]
Hi Fernando. You can see `Server` and `Port` field under Blynk configuration. You can set there.
Also, please test a lot before if you want to use it, because it's a very immature library, something can go wrong.

![49258236-ff176480-f434-11e8-9430-61cb09d8e6bd](https://user-images.githubusercontent.com/33419552/49364409-90f8c900-f6e4-11e8-97d3-1e69cdde251a.png)


Thanks.
